#!/bin/sh

#Constants
RED='\033[0;31m'
WHITE='\033[0;37m'

CURRBRANCH="$(git branch --show-current)"


if [[ $CURRBRANCH == "development" || $CURRBRANCH == "master" ]]; 
then
	echo ""
	echo -e "\tCannot commit to this branch!"
	echo -e "\t${RED}You are trying to commit to $CURRBRANCH"
	echo -e "\t${WHITE}By agreed convention we should create feature branch and commit there"
	echo ""	
	exit 1
fi

exit 0