#!/bin/sh

#Constants pre commit
RED='\033[0;31m'
WHITE='\033[0;37m'

CURRBRANCH="$(git branch --show-current)"

SECRETFILE=".githooks/secret.txt"

LISTOFFILES="$(git diff --name-only --cached)"
GIT='git --git-dir='$PWD'/.git'

if [[ $CURRBRANCH == "development" || $CURRBRANCH == "master" ]]; 
then
	echo ""
	echo -e "\t${RED}Cannot commit to this branch!"
	echo -e "\t${WHITE}You are trying to commit to $CURRBRANCH"
	echo -e "\tBy agreed convention we should create feature branch and commit there"
	echo ""	
	exit 1
fi

if [[ -n "$LISTOFFILES" ]];
then
	
	exec < /dev/tty
	
	cd $BASEDIRPSW

	if [[ -f "$SECRETFILE" ]];
	then
		SECRET="$(cat .githooks/secret.txt)"
		EXISTS=0
	else
		EXISTS=1
	fi

	if [[ $EXISTS == 0 ]];
	then
		echo "$(clear)"
		echo -e "  Changes were made to .githooks..."
		echo -e "  To verify your identity enter password"
		read -sp "  Enter your password: " PASSWD
		echo ""

		INPUTHASHED="$(openssl passwd -1 -salt "salt" $PASSWD)"
		if [[ $INPUTHASHED == $SECRET ]];
		then
			COMMIT=0
			echo "$(clear)"
			echo -e "  Access granted, commiting changes to hooks"
			echo ""
		else
			COMMIT=1
			echo "$(clear)"
			echo -e "  Access denied, reverting changes for hook files"
			echo ""
		fi
	else
		COMMIT=1
		echo "$(clear)"
		echo -e "  secret.txt doesn't exist, contact devs"
		echo ""
	fi

	if [[ $COMMIT == 1 ]];
	then
		for file in "${LISTOFFILES[@]}"
		do
			echo "$(git checkout HEAD -- $file)"
			echo "  Reverting file to original state : $file"
		done
	fi
	
fi

exit 0