CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Medicines" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_Medicines" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211108013324_InitialMigration', '5.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "Countries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_Countries" PRIMARY KEY ("Id")
);

CREATE TABLE "Cities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "PostalCode" integer NOT NULL,
    "CountryId" integer NOT NULL,
    CONSTRAINT "PK_Cities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Cities_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Countries" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Hospitals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "StreetNumber" text NULL,
    "StreetName" text NULL,
    "CityId" integer NOT NULL,
    "ApiKey" uuid NOT NULL,
    CONSTRAINT "PK_Hospitals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Hospitals_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Complaints" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NULL,
    "Description" text NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "HospitalId" integer NOT NULL,
    CONSTRAINT "PK_Complaints" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Complaints_Hospitals_HospitalId" FOREIGN KEY ("HospitalId") REFERENCES "Hospitals" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ComplaintResponses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Text" text NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "ComplaintId" integer NOT NULL,
    CONSTRAINT "PK_ComplaintResponses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ComplaintResponses_Complaints_ComplaintId" FOREIGN KEY ("ComplaintId") REFERENCES "Complaints" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Cities_CountryId" ON "Cities" ("CountryId");

CREATE INDEX "IX_ComplaintResponses_ComplaintId" ON "ComplaintResponses" ("ComplaintId");

CREATE INDEX "IX_Complaints_HospitalId" ON "Complaints" ("HospitalId");

CREATE INDEX "IX_Hospitals_CityId" ON "Hospitals" ("CityId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211116160313_CreatedComplaintsAndHospital', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Hospitals" ADD "BaseUrl" text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211119115435_AddedBaseUrlHospital', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Medicines" ADD "MainPrecautions" text[] NULL;

ALTER TABLE "Medicines" ADD "ManufacturerId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Medicines" ADD "MedicinesThatCanBeCombined" text[] NULL;

ALTER TABLE "Medicines" ADD "PotentialDangers" text[] NULL;

ALTER TABLE "Medicines" ADD "Reactions" text[] NULL;

ALTER TABLE "Medicines" ADD "SideEffects" text[] NULL;

ALTER TABLE "Medicines" ADD "Substances" text[] NULL;

ALTER TABLE "Medicines" ADD "Type" text NULL;

ALTER TABLE "Medicines" ADD "Usage" text NULL;

ALTER TABLE "Medicines" ADD "Weight" double precision NOT NULL DEFAULT 0.0;

CREATE TABLE "Manufacturers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_Manufacturers" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Medicines_ManufacturerId" ON "Medicines" ("ManufacturerId");

ALTER TABLE "Medicines" ADD CONSTRAINT "FK_Medicines_Manufacturers_ManufacturerId" FOREIGN KEY ("ManufacturerId") REFERENCES "Manufacturers" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211119163359_MedicineModelInitial', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Medicines" RENAME COLUMN "Weight" TO "WeightInMilligrams";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211119171802_MedicineModelSecond', '5.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211119173915_MedicineModelFinal', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Medicines" ADD "Quantity" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211120155050_AddedQuantity', '5.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "MedicineReportFiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FileName" text NULL,
    "Host" text NULL,
    CONSTRAINT "PK_MedicineReportFiles" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211120173954_AddedMedicineReportFile', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "MedicineReportFiles" ADD "HospitalId" integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_MedicineReportFiles_HospitalId" ON "MedicineReportFiles" ("HospitalId");

ALTER TABLE "MedicineReportFiles" ADD CONSTRAINT "FK_MedicineReportFiles_Hospitals_HospitalId" FOREIGN KEY ("HospitalId") REFERENCES "Hospitals" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211120174117_AddedHospitalInReport', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Medicines" DROP COLUMN "MainPrecautions";

ALTER TABLE "Medicines" DROP COLUMN "MedicinesThatCanBeCombined";

ALTER TABLE "Medicines" DROP COLUMN "PotentialDangers";

ALTER TABLE "Medicines" DROP COLUMN "Reactions";

ALTER TABLE "Medicines" DROP COLUMN "SideEffects";

ALTER TABLE "Medicines" DROP COLUMN "Substances";

CREATE TABLE "MedicineCombinations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstMedicineId" integer NOT NULL,
    "SecondMedicineId" integer NOT NULL,
    CONSTRAINT "PK_MedicineCombinations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MedicineCombinations_Medicines_FirstMedicineId" FOREIGN KEY ("FirstMedicineId") REFERENCES "Medicines" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MedicineCombinations_Medicines_SecondMedicineId" FOREIGN KEY ("SecondMedicineId") REFERENCES "Medicines" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MedicinePotentialDangers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "MedicineId" integer NULL,
    CONSTRAINT "PK_MedicinePotentialDangers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MedicinePotentialDangers_Medicines_MedicineId" FOREIGN KEY ("MedicineId") REFERENCES "Medicines" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Precautions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "MedicineId" integer NULL,
    CONSTRAINT "PK_Precautions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Precautions_Medicines_MedicineId" FOREIGN KEY ("MedicineId") REFERENCES "Medicines" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Reactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "MedicineId" integer NULL,
    CONSTRAINT "PK_Reactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reactions_Medicines_MedicineId" FOREIGN KEY ("MedicineId") REFERENCES "Medicines" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "SideEffects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "MedicineId" integer NULL,
    CONSTRAINT "PK_SideEffects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SideEffects_Medicines_MedicineId" FOREIGN KEY ("MedicineId") REFERENCES "Medicines" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Substances" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "MedicineId" integer NULL,
    CONSTRAINT "PK_Substances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Substances_Medicines_MedicineId" FOREIGN KEY ("MedicineId") REFERENCES "Medicines" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_MedicineCombinations_FirstMedicineId" ON "MedicineCombinations" ("FirstMedicineId");

CREATE INDEX "IX_MedicineCombinations_SecondMedicineId" ON "MedicineCombinations" ("SecondMedicineId");

CREATE INDEX "IX_MedicinePotentialDangers_MedicineId" ON "MedicinePotentialDangers" ("MedicineId");

CREATE INDEX "IX_Precautions_MedicineId" ON "Precautions" ("MedicineId");

CREATE INDEX "IX_Reactions_MedicineId" ON "Reactions" ("MedicineId");

CREATE INDEX "IX_SideEffects_MedicineId" ON "SideEffects" ("MedicineId");

CREATE INDEX "IX_Substances_MedicineId" ON "Substances" ("MedicineId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211121230825_MedicineModelRefactored', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Precautions" DROP CONSTRAINT "FK_Precautions_Medicines_MedicineId";

ALTER TABLE "Reactions" DROP CONSTRAINT "FK_Reactions_Medicines_MedicineId";

ALTER TABLE "SideEffects" DROP CONSTRAINT "FK_SideEffects_Medicines_MedicineId";

ALTER TABLE "Substances" DROP CONSTRAINT "FK_Substances_Medicines_MedicineId";

DROP INDEX "IX_Substances_MedicineId";

DROP INDEX "IX_SideEffects_MedicineId";

DROP INDEX "IX_Reactions_MedicineId";

DROP INDEX "IX_Precautions_MedicineId";

ALTER TABLE "Substances" DROP COLUMN "MedicineId";

ALTER TABLE "SideEffects" DROP COLUMN "MedicineId";

ALTER TABLE "Reactions" DROP COLUMN "MedicineId";

ALTER TABLE "Precautions" DROP COLUMN "MedicineId";

CREATE TABLE "MedicinePrecaution" (
    "MedicinesId" integer NOT NULL,
    "PrecautionsId" integer NOT NULL,
    CONSTRAINT "PK_MedicinePrecaution" PRIMARY KEY ("MedicinesId", "PrecautionsId"),
    CONSTRAINT "FK_MedicinePrecaution_Medicines_MedicinesId" FOREIGN KEY ("MedicinesId") REFERENCES "Medicines" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MedicinePrecaution_Precautions_PrecautionsId" FOREIGN KEY ("PrecautionsId") REFERENCES "Precautions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MedicineReaction" (
    "MedicinesId" integer NOT NULL,
    "ReactionsId" integer NOT NULL,
    CONSTRAINT "PK_MedicineReaction" PRIMARY KEY ("MedicinesId", "ReactionsId"),
    CONSTRAINT "FK_MedicineReaction_Medicines_MedicinesId" FOREIGN KEY ("MedicinesId") REFERENCES "Medicines" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MedicineReaction_Reactions_ReactionsId" FOREIGN KEY ("ReactionsId") REFERENCES "Reactions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MedicineSideEffect" (
    "MedicinesId" integer NOT NULL,
    "SideEffectsId" integer NOT NULL,
    CONSTRAINT "PK_MedicineSideEffect" PRIMARY KEY ("MedicinesId", "SideEffectsId"),
    CONSTRAINT "FK_MedicineSideEffect_Medicines_MedicinesId" FOREIGN KEY ("MedicinesId") REFERENCES "Medicines" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MedicineSideEffect_SideEffects_SideEffectsId" FOREIGN KEY ("SideEffectsId") REFERENCES "SideEffects" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MedicineSubstance" (
    "MedicinesId" integer NOT NULL,
    "SubstancesId" integer NOT NULL,
    CONSTRAINT "PK_MedicineSubstance" PRIMARY KEY ("MedicinesId", "SubstancesId"),
    CONSTRAINT "FK_MedicineSubstance_Medicines_MedicinesId" FOREIGN KEY ("MedicinesId") REFERENCES "Medicines" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MedicineSubstance_Substances_SubstancesId" FOREIGN KEY ("SubstancesId") REFERENCES "Substances" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_MedicinePrecaution_PrecautionsId" ON "MedicinePrecaution" ("PrecautionsId");

CREATE INDEX "IX_MedicineReaction_ReactionsId" ON "MedicineReaction" ("ReactionsId");

CREATE INDEX "IX_MedicineSideEffect_SideEffectsId" ON "MedicineSideEffect" ("SideEffectsId");

CREATE INDEX "IX_MedicineSubstance_SubstancesId" ON "MedicineSubstance" ("SubstancesId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211122164009_FixedManyToManyRelationshipForMedicine', '5.0.11');

COMMIT;

START TRANSACTION;

DROP TABLE "MedicinePotentialDangers";

DROP TABLE "MedicinePrecaution";

DROP TABLE "MedicineReaction";

DROP TABLE "MedicineSideEffect";

DROP TABLE "Precautions";

DROP TABLE "Reactions";

DROP TABLE "SideEffects";

ALTER TABLE "Medicines" ADD "MedicinePotentialDangers" text NULL;

ALTER TABLE "Medicines" ADD "Precautions" text NULL;

ALTER TABLE "Medicines" ADD "Reactions" text NULL;

ALTER TABLE "Medicines" ADD "SideEffects" text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211122214444_ChangedMedicineReferencesBackToStrings', '5.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "Benefits" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NULL,
    "Description" text NULL,
    "StartTime" timestamp without time zone NOT NULL,
    "EndTime" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Benefits" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211123003603_AddedBenefit', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "MedicineReportFiles" ADD "ReceivedDate" timestamp without time zone NOT NULL DEFAULT TIMESTAMP '0001-01-01 00:00:00';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211204190115_MedicineReportFileAddedReceivedDate', '5.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "TenderOffer" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MedicineId" integer NOT NULL,
    "HospitalId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "CreationTime" timestamp without time zone NOT NULL,
    "IsConfirmed" boolean NOT NULL,
    CONSTRAINT "PK_TenderOffer" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TenderOffer_Hospitals_HospitalId" FOREIGN KEY ("HospitalId") REFERENCES "Hospitals" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TenderOffer_Medicines_MedicineId" FOREIGN KEY ("MedicineId") REFERENCES "Medicines" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TenderOffer_HospitalId" ON "TenderOffer" ("HospitalId");

CREATE INDEX "IX_TenderOffer_MedicineId" ON "TenderOffer" ("MedicineId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211212220556_TenderOffersAdded', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Medicines" ADD "Price" double precision NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211213002026_MedicinePriceAdded', '5.0.11');

COMMIT;

