CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256) NULL,
    "NormalizedName" character varying(256) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "Countries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_Countries" PRIMARY KEY ("Id")
);

CREATE TABLE "InventoryItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "InventoryItemType" integer NOT NULL,
    CONSTRAINT "PK_InventoryItems" PRIMARY KEY ("Id")
);

CREATE TABLE "MedicationIngredients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_MedicationIngredients" PRIMARY KEY ("Id")
);

CREATE TABLE "Medications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "TimesPerDay" integer NOT NULL,
    "HowToUse" text NULL,
    CONSTRAINT "PK_Medications" PRIMARY KEY ("Id")
);

CREATE TABLE "Rooms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    "DimensionX" double precision NOT NULL,
    "DimensionY" double precision NOT NULL,
    "FloorNumber" integer NOT NULL,
    "BuildingName" text NULL,
    CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id")
);

CREATE TABLE "Specializations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    CONSTRAINT "PK_Specializations" PRIMARY KEY ("Id")
);

CREATE TABLE "Surveys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CreatedDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Surveys" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Cities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "PostalCode" integer NOT NULL,
    "CountryId" integer NOT NULL,
    CONSTRAINT "PK_Cities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Cities_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Countries" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MedicationMedicationIngredient" (
    "MedicationIngredientsId" integer NOT NULL,
    "MedicationsId" integer NOT NULL,
    CONSTRAINT "PK_MedicationMedicationIngredient" PRIMARY KEY ("MedicationIngredientsId", "MedicationsId"),
    CONSTRAINT "FK_MedicationMedicationIngredient_MedicationIngredients_Medica~" FOREIGN KEY ("MedicationIngredientsId") REFERENCES "MedicationIngredients" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MedicationMedicationIngredient_Medications_MedicationsId" FOREIGN KEY ("MedicationsId") REFERENCES "Medications" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RoomInventories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoomId" integer NOT NULL,
    "InventoryItemId" integer NOT NULL,
    "Amount" integer NOT NULL,
    CONSTRAINT "PK_RoomInventories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoomInventories_InventoryItems_InventoryItemId" FOREIGN KEY ("InventoryItemId") REFERENCES "InventoryItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RoomInventories_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Questions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Text" text NULL,
    "Category" integer NOT NULL,
    "SurveyId" integer NOT NULL,
    CONSTRAINT "PK_Questions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Questions_Surveys_SurveyId" FOREIGN KEY ("SurveyId") REFERENCES "Surveys" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AnsweredQuestions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "QuestionId" integer NOT NULL,
    "Rating" integer NOT NULL,
    "Category" integer NOT NULL,
    "AnsweredSurveyId" integer NOT NULL,
    CONSTRAINT "PK_AnsweredQuestions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AnsweredQuestions_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ScheduledEvents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ScheduledEventType" integer NOT NULL,
    "IsCanceled" boolean NOT NULL,
    "IsDone" boolean NOT NULL,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL,
    "PatientId" integer NULL,
    "DoctorId" integer NULL,
    "RoomId" integer NULL,
    "AnsweredSurveyId" integer NOT NULL,
    "MedicalRecordId" integer NULL,
    CONSTRAINT "PK_ScheduledEvents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ScheduledEvents_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Allergies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" integer NULL,
    "MedicationIngredientId" integer NULL,
    "MedicalIngredientId" integer NOT NULL,
    "MedicalRecordId" integer NULL,
    CONSTRAINT "PK_Allergies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Allergies_MedicationIngredients_MedicationIngredientId" FOREIGN KEY ("MedicationIngredientId") REFERENCES "MedicationIngredients" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "AnsweredSurveys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AnsweredDate" timestamp without time zone NOT NULL,
    "SurveyId" integer NOT NULL,
    "PatientId" integer NULL,
    CONSTRAINT "PK_AnsweredSurveys" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AnsweredSurveys_Surveys_SurveyId" FOREIGN KEY ("SurveyId") REFERENCES "Surveys" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey")
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" integer NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text NULL,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name")
);

CREATE TABLE "Feedbacks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" integer NULL,
    "FeedbackStatus" integer NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    "Text" text NULL,
    "IsPublishable" boolean NOT NULL,
    CONSTRAINT "PK_Feedbacks" PRIMARY KEY ("Id")
);

CREATE TABLE "MedicalRecords" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Height" double precision NOT NULL,
    "Weight" double precision NOT NULL,
    "DoctorId" integer NULL,
    "BloodType" integer NOT NULL,
    "JobStatus" integer NOT NULL,
    CONSTRAINT "PK_MedicalRecords" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NULL,
    "MiddleName" text NULL,
    "LastName" text NULL,
    "DateOfBirth" timestamp without time zone NOT NULL,
    "Gender" integer NOT NULL,
    "Street" text NULL,
    "StreetNumber" text NULL,
    "CityId" integer NOT NULL,
    "Discriminator" text NOT NULL,
    "MedicalRecordId" integer NULL,
    "IsBlocked" boolean NULL,
    "RoomId" integer NULL,
    "SpecializationId" integer NULL,
    "UserName" character varying(256) NULL,
    "NormalizedUserName" character varying(256) NULL,
    "Email" character varying(256) NULL,
    "NormalizedEmail" character varying(256) NULL,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text NULL,
    "SecurityStamp" text NULL,
    "ConcurrencyStamp" text NULL,
    "PhoneNumber" text NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone NULL,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUsers_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUsers_MedicalRecords_MedicalRecordId" FOREIGN KEY ("MedicalRecordId") REFERENCES "MedicalRecords" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUsers_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUsers_Specializations_SpecializationId" FOREIGN KEY ("SpecializationId") REFERENCES "Specializations" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Diagnoses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Illness" text NULL,
    "Symptoms" text NULL,
    "Anamnesis" text NULL,
    "Date" timestamp without time zone NOT NULL,
    "MedicalRecordId" integer NULL,
    CONSTRAINT "PK_Diagnoses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Diagnoses_MedicalRecords_MedicalRecordId" FOREIGN KEY ("MedicalRecordId") REFERENCES "MedicalRecords" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "HospitalTreatments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL,
    "Reason" text NULL,
    "RoomId" integer NULL,
    "MedicalRecordId" integer NULL,
    CONSTRAINT "PK_HospitalTreatments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HospitalTreatments_MedicalRecords_MedicalRecordId" FOREIGN KEY ("MedicalRecordId") REFERENCES "MedicalRecords" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_HospitalTreatments_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Prescriptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" integer NULL,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL,
    "IssuedDate" timestamp without time zone NOT NULL,
    "MedicationId" integer NOT NULL,
    "MedicalRecordId" integer NULL,
    CONSTRAINT "PK_Prescriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Prescriptions_AspNetUsers_PatientId" FOREIGN KEY ("PatientId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Prescriptions_MedicalRecords_MedicalRecordId" FOREIGN KEY ("MedicalRecordId") REFERENCES "MedicalRecords" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Prescriptions_Medications_MedicationId" FOREIGN KEY ("MedicationId") REFERENCES "Medications" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Referrals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IssuedDate" timestamp without time zone NOT NULL,
    "IsUrgent" boolean NOT NULL,
    "Description" text NULL,
    "DoctorId" integer NULL,
    "MedicalRecordId" integer NULL,
    CONSTRAINT "PK_Referrals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Referrals_AspNetUsers_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Referrals_MedicalRecords_MedicalRecordId" FOREIGN KEY ("MedicalRecordId") REFERENCES "MedicalRecords" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Allergies_MedicalRecordId" ON "Allergies" ("MedicalRecordId");

CREATE INDEX "IX_Allergies_MedicationIngredientId" ON "Allergies" ("MedicationIngredientId");

CREATE INDEX "IX_Allergies_PatientId" ON "Allergies" ("PatientId");

CREATE INDEX "IX_AnsweredQuestions_AnsweredSurveyId" ON "AnsweredQuestions" ("AnsweredSurveyId");

CREATE INDEX "IX_AnsweredQuestions_QuestionId" ON "AnsweredQuestions" ("QuestionId");

CREATE INDEX "IX_AnsweredSurveys_PatientId" ON "AnsweredSurveys" ("PatientId");

CREATE INDEX "IX_AnsweredSurveys_SurveyId" ON "AnsweredSurveys" ("SurveyId");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE INDEX "IX_AspNetUsers_CityId" ON "AspNetUsers" ("CityId");

CREATE UNIQUE INDEX "IX_AspNetUsers_MedicalRecordId" ON "AspNetUsers" ("MedicalRecordId");

CREATE INDEX "IX_AspNetUsers_RoomId" ON "AspNetUsers" ("RoomId");

CREATE INDEX "IX_AspNetUsers_SpecializationId" ON "AspNetUsers" ("SpecializationId");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_Cities_CountryId" ON "Cities" ("CountryId");

CREATE INDEX "IX_Diagnoses_MedicalRecordId" ON "Diagnoses" ("MedicalRecordId");

CREATE INDEX "IX_Feedbacks_PatientId" ON "Feedbacks" ("PatientId");

CREATE INDEX "IX_HospitalTreatments_MedicalRecordId" ON "HospitalTreatments" ("MedicalRecordId");

CREATE INDEX "IX_HospitalTreatments_RoomId" ON "HospitalTreatments" ("RoomId");

CREATE INDEX "IX_MedicalRecords_DoctorId" ON "MedicalRecords" ("DoctorId");

CREATE INDEX "IX_MedicationMedicationIngredient_MedicationsId" ON "MedicationMedicationIngredient" ("MedicationsId");

CREATE INDEX "IX_Prescriptions_MedicalRecordId" ON "Prescriptions" ("MedicalRecordId");

CREATE INDEX "IX_Prescriptions_MedicationId" ON "Prescriptions" ("MedicationId");

CREATE INDEX "IX_Prescriptions_PatientId" ON "Prescriptions" ("PatientId");

CREATE INDEX "IX_Questions_SurveyId" ON "Questions" ("SurveyId");

CREATE INDEX "IX_Referrals_DoctorId" ON "Referrals" ("DoctorId");

CREATE INDEX "IX_Referrals_MedicalRecordId" ON "Referrals" ("MedicalRecordId");

CREATE INDEX "IX_RoomInventories_InventoryItemId" ON "RoomInventories" ("InventoryItemId");

CREATE INDEX "IX_RoomInventories_RoomId" ON "RoomInventories" ("RoomId");

CREATE INDEX "IX_ScheduledEvents_AnsweredSurveyId" ON "ScheduledEvents" ("AnsweredSurveyId");

CREATE INDEX "IX_ScheduledEvents_DoctorId" ON "ScheduledEvents" ("DoctorId");

CREATE INDEX "IX_ScheduledEvents_MedicalRecordId" ON "ScheduledEvents" ("MedicalRecordId");

CREATE INDEX "IX_ScheduledEvents_PatientId" ON "ScheduledEvents" ("PatientId");

CREATE INDEX "IX_ScheduledEvents_RoomId" ON "ScheduledEvents" ("RoomId");

ALTER TABLE "AnsweredQuestions" ADD CONSTRAINT "FK_AnsweredQuestions_AnsweredSurveys_AnsweredSurveyId" FOREIGN KEY ("AnsweredSurveyId") REFERENCES "AnsweredSurveys" ("Id") ON DELETE CASCADE;

ALTER TABLE "ScheduledEvents" ADD CONSTRAINT "FK_ScheduledEvents_AnsweredSurveys_AnsweredSurveyId" FOREIGN KEY ("AnsweredSurveyId") REFERENCES "AnsweredSurveys" ("Id") ON DELETE CASCADE;

ALTER TABLE "ScheduledEvents" ADD CONSTRAINT "FK_ScheduledEvents_AspNetUsers_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

ALTER TABLE "ScheduledEvents" ADD CONSTRAINT "FK_ScheduledEvents_AspNetUsers_PatientId" FOREIGN KEY ("PatientId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

ALTER TABLE "ScheduledEvents" ADD CONSTRAINT "FK_ScheduledEvents_MedicalRecords_MedicalRecordId" FOREIGN KEY ("MedicalRecordId") REFERENCES "MedicalRecords" ("Id") ON DELETE RESTRICT;

ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "Allergies" ADD CONSTRAINT "FK_Allergies_AspNetUsers_PatientId" FOREIGN KEY ("PatientId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Allergies" ADD CONSTRAINT "FK_Allergies_MedicalRecords_MedicalRecordId" FOREIGN KEY ("MedicalRecordId") REFERENCES "MedicalRecords" ("Id") ON DELETE RESTRICT;

ALTER TABLE "AnsweredSurveys" ADD CONSTRAINT "FK_AnsweredSurveys_AspNetUsers_PatientId" FOREIGN KEY ("PatientId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

ALTER TABLE "AspNetUserClaims" ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "AspNetUserLogins" ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "AspNetUserTokens" ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "Feedbacks" ADD CONSTRAINT "FK_Feedbacks_AspNetUsers_PatientId" FOREIGN KEY ("PatientId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

ALTER TABLE "MedicalRecords" ADD CONSTRAINT "FK_MedicalRecords_AspNetUsers_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211122074408_LatestChanges', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Rooms" ADD "RoomType" integer NOT NULL DEFAULT 0;

CREATE TABLE "EquipmentTransferEvents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL,
    "InitalRoomId" integer NULL,
    "DestinationRoomId" integer NULL,
    "InventoryItemId" integer NULL,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_EquipmentTransferEvents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EquipmentTransferEvents_InventoryItems_InventoryItemId" FOREIGN KEY ("InventoryItemId") REFERENCES "InventoryItems" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_EquipmentTransferEvents_Rooms_DestinationRoomId" FOREIGN KEY ("DestinationRoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_EquipmentTransferEvents_Rooms_InitalRoomId" FOREIGN KEY ("InitalRoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_EquipmentTransferEvents_DestinationRoomId" ON "EquipmentTransferEvents" ("DestinationRoomId");

CREATE INDEX "IX_EquipmentTransferEvents_InitalRoomId" ON "EquipmentTransferEvents" ("InitalRoomId");

CREATE INDEX "IX_EquipmentTransferEvents_InventoryItemId" ON "EquipmentTransferEvents" ("InventoryItemId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211122074409_AddedEquipmentTransferEvent', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "AnsweredSurveys" DROP CONSTRAINT "FK_AnsweredSurveys_AspNetUsers_PatientId";

ALTER TABLE "MedicalRecords" DROP CONSTRAINT "FK_MedicalRecords_AspNetUsers_DoctorId";

ALTER TABLE "MedicalRecords" ALTER COLUMN "DoctorId" SET NOT NULL;
ALTER TABLE "MedicalRecords" ALTER COLUMN "DoctorId" SET DEFAULT 0;

ALTER TABLE "AnsweredSurveys" ALTER COLUMN "PatientId" SET NOT NULL;
ALTER TABLE "AnsweredSurveys" ALTER COLUMN "PatientId" SET DEFAULT 0;

ALTER TABLE "AnsweredSurveys" ADD CONSTRAINT "FK_AnsweredSurveys_AspNetUsers_PatientId" FOREIGN KEY ("PatientId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "MedicalRecords" ADD CONSTRAINT "FK_MedicalRecords_AspNetUsers_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211203124909_MedRecUpdated', '5.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "MedicationExpenditureLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MedicationId" integer NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "AmountSpent" integer NOT NULL,
    CONSTRAINT "PK_MedicationExpenditureLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MedicationExpenditureLogs_Medications_MedicationId" FOREIGN KEY ("MedicationId") REFERENCES "Medications" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_MedicationExpenditureLogs_MedicationId" ON "MedicationExpenditureLogs" ("MedicationId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211204181012_MedicationExpenditureLogsAdded', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "EquipmentTransferEvents" DROP CONSTRAINT "FK_EquipmentTransferEvents_Rooms_InitalRoomId";

ALTER TABLE "Rooms" RENAME COLUMN "DimensionY" TO "Width";

ALTER TABLE "Rooms" RENAME COLUMN "DimensionX" TO "Height";

ALTER TABLE "EquipmentTransferEvents" RENAME COLUMN "InitalRoomId" TO "InitialRoomId";

ALTER INDEX "IX_EquipmentTransferEvents_InitalRoomId" RENAME TO "IX_EquipmentTransferEvents_InitialRoomId";

CREATE TABLE "RoomPositions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoomId" integer NOT NULL,
    "DimensionX" double precision NOT NULL,
    "DimensionY" double precision NOT NULL,
    "Width" double precision NOT NULL,
    "Height" double precision NOT NULL,
    CONSTRAINT "PK_RoomPositions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoomPositions_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RoomRenovationEvents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL,
    "RoomId" integer NULL,
    "IsMerge" boolean NOT NULL,
    "MergeRoomId" integer NULL,
    "IsCanceled" boolean NOT NULL,
    "IsDone" boolean NOT NULL,
    CONSTRAINT "PK_RoomRenovationEvents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoomRenovationEvents_Rooms_MergeRoomId" FOREIGN KEY ("MergeRoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RoomRenovationEvents_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_RoomPositions_RoomId" ON "RoomPositions" ("RoomId");

CREATE INDEX "IX_RoomRenovationEvents_MergeRoomId" ON "RoomRenovationEvents" ("MergeRoomId");

CREATE INDEX "IX_RoomRenovationEvents_RoomId" ON "RoomRenovationEvents" ("RoomId");

ALTER TABLE "EquipmentTransferEvents" ADD CONSTRAINT "FK_EquipmentTransferEvents_Rooms_InitialRoomId" FOREIGN KEY ("InitialRoomId") REFERENCES "Rooms" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211207011211_RoomPositionAdded', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "ScheduledEvents" DROP CONSTRAINT "FK_ScheduledEvents_AnsweredSurveys_AnsweredSurveyId";

DROP INDEX "IX_ScheduledEvents_AnsweredSurveyId";

ALTER TABLE "ScheduledEvents" DROP COLUMN "AnsweredSurveyId";

ALTER TABLE "AnsweredSurveys" ADD "ScheduledEventId" integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_AnsweredSurveys_ScheduledEventId" ON "AnsweredSurveys" ("ScheduledEventId");

ALTER TABLE "AnsweredSurveys" ADD CONSTRAINT "FK_AnsweredSurveys_ScheduledEvents_ScheduledEventId" FOREIGN KEY ("ScheduledEventId") REFERENCES "ScheduledEvents" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211208214210_SurveyMigration', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "RoomRenovationEvents" DROP COLUMN "IsCanceled";

ALTER TABLE "RoomRenovationEvents" DROP COLUMN "IsDone";

ALTER TABLE "RoomRenovationEvents" ADD "FirstRoomDescription" text NULL;

ALTER TABLE "RoomRenovationEvents" ADD "FirstRoomName" text NULL;

ALTER TABLE "RoomRenovationEvents" ADD "FirstRoomType" integer NOT NULL DEFAULT 0;

ALTER TABLE "RoomRenovationEvents" ADD "SecondRoomDescription" text NULL;

ALTER TABLE "RoomRenovationEvents" ADD "SecondRoomName" text NULL;

ALTER TABLE "RoomRenovationEvents" ADD "SecondRoomType" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211209175906_RoomRenovationEventUpdated', '5.0.11');

COMMIT;

